#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
## Note: anything with a ## comment is an SRB addition


##### Browser #####

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

##### Editors/Pagers #####

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# LESS syntax highlight
# Setup: "brew install highlight"
# Pipe Highlight to less
export LESSOPEN="| $(which highlight) %s --out-format xterm256 --line-numbers --quiet --force --style solarized-light"
export LESS=" -R"
alias less='less -m -N -g -i -J --line-numbers --underline-special'
alias more='less'

# Use "highlight" in place of "cat"
alias hcat="highlight $0 --out-format xterm256 --line-numbers --quiet --force --style solarized-light"



##### Language #####

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

export LC_ALL='en_US.UTF-8'
export TERM='xterm-256color'

##### PATH variable #####

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

## for custom user programs
PATH=/Users/srbutler/bin:"$PATH"

## apache ant and ivy (only at work)
# PATH=/Users/srbutler/bin/ant/bin:"$PATH"
# export ANT_HOME=/Users/srbutler/bin/ant

## haskell cabal and bin directories
PATH=/Users/srbutler/.cabal/bin:"$PATH"
PATH=/Users/srbutler/.local/bin:"$PATH"

## rust cargo directory
PATH=/Users/srbutler/.cargo/bin:"$PATH"
export RUST_SRC_PATH=/Users/srbutler/.multirust/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src

## golang path and root
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/.go
PATH="$PATH":"$GOROOT"/bin:"$GOPATH"/bin

## node.js npm directory
# PATH=/usr/local/share/npm/bin:"$PATH"

## pyenv shims
PATH=/Users/srbutler/.pyenv/shims:"$PATH"
source ~/.pyenv/completions/pyenv.zsh
## disable the prompt stating the env, will be disabled soon
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# for sublimetext3 linter
# export PATH=/opt/bin:$PATH

# android SDK
export ANDROID_HOME=~/Library/Android/sdk/sources/android-23
PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path


##### Temporary Files #####

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
# Initialization for FDK command line tools.Mon Jan 11 17:32:24 2016
FDK_EXE="/Users/srbutler/bin/FDK/Tools/osx"
PATH=${PATH}:"/Users/srbutler/bin/FDK/Tools/osx"
export PATH
export FDK_EXE


#### Miscellaneous ####

## add git-prompts to zsh
source ~/.git-prompt.sh


## use pygments as gtags backend
export GTAGSLABEL=pygments

## adds pip completions to zsh
# pip zsh completion start
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
compctl -K _pip_completion pip
# pip zsh completion end

# add docker for developers
d4dconfig="$HOME/docker4developers/bin/config.sh"
if [[ -a "$d4dconfig" ]]; then
    source "$d4dconfig"
fi


