#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
## Note: anything with a ## comment is an SRB addition


##### Browser #####

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

##### Editors/Pagers #####

export EDITOR='emacs'
export VISUAL='emacs'
export PAGER='less'

##### Language #####

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

export LC_ALL='en_US.UTF-8'
export TERM='xterm-256color'

##### PATH variable #####

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )
fpath+=("modules/prompt/external/pure/async.zsh")

## for custom user programs
PATH=$HOME/bin:"$PATH"

##### Temporary Files #####

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

## Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path
