#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
## Note: anything with a ## comment is an SRB addition


##### Browser #####

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

##### Editors/Pagers #####

export EDITOR='emacs'
export VISUAL='emacs'
export PAGER='less'

# LESS syntax highlight
# Setup: "brew install highlight"
# Pipe Highlight to less
export LESS=" -R"
alias less='less -m -N -g -i -J --line-numbers --underline-special'
alias more='less'


##### Language #####

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

export LC_ALL='en_US.UTF-8'
export TERM='xterm-256color'

##### PATH variable #####

## golang path and root
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/.go


##### Temporary Files #####

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#### Miscellaneous ####

## adds pip completions to zsh
# pip zsh completion start
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
compctl -K _pip_completion pip

## Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path
