#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# for emacs ansi-term to play nicely
if [[ -n ${EMACS} ]]; then
    zstyle ':prezto:module:terminal' auto-title 'no'
fi

## use pygments as gtags backend
#export GTAGSLABEL=pygments

PURE_PROMPT_SYMBOL=">"
PURE_PROMPT_VICMD_SYMBOL="<"
PURE_GIT_DOWN_ARROW="v"
PURE_GIT_UP_ARROW="^"

## for custom user programs
export PATH=$HOME/bin:"$PATH"
export PATH=$HOME/.local/bin:"$PATH"

## "fake" NPM global installation
NPM_PACKAGES="${HOME}/mbig/.npm-packages"
PATH="$NPM_PACKAGES/bin:$PATH"

fpath+=("modules/prompt/external/pure/async.zsh")

## Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path
