#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# zmodload zsh/zprof


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

##### Aliases #####

# ls
alias la='ls -lhA'
alias ll='ls -lh'


## git
alias gws='git status'
alias gwS='git status --short'
alias gds='git diff --staged'
alias gp='git pull'
alias gpo='git pull origin'
alias grh='git reset HEAD'

## emacs
alias e='emacsclient'

## other/misc.
alias cll='clear & ll'

#### Utilities ####

# update fpath for pure prompt
fpath=( "$HOME/.zfunctions" $fpath )
autoload -U promptinit; promptinit

PURE_PROMPT_SYMBOL=">"
prompt pure

# general zsh completions
# https://github.com/zsh-users/zsh-completions
#fpath=(/usr/local/share/zsh-completions $fpath)

## Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

## ensure emacs keybindings are used
bindkey -e
